# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jimmie Gmaz, PhD
# Description of the Site
description: Research Scientist
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: 'background.jpeg'

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jim.gmaz@gmail.com
# facebook_username: /
linkedin_username: jimmie-gmaz
twitter_username: j_gmaz
# instagram_username: /
# github_username:  /
# youtube_channel_id: /
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: G-RS2VF1WLSD

# Disqus
# disqus-shortname: thedevslot

# Name of the Author
author-name: Jimmie Gmaz
# URL for the Image of the Author
# author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# author-image: https://github.com/jgmaz/WhatATheme/tree/master/assets/images/headshot.jpeg
author-image: 'assets/images/headshot.jpeg'

# 60 Words About the Author
author-about: |
  I am a scientist with over a decade of experience in end-to-end neuroscience research from initial conception through to the dissemination of results. I utilize in vivo experimental techniques to acquire neurophysiological data, and apply various signal processing and machine learning methods to extract meaningful insights. <br> <br> 
  Currently in <a href="https://beneuro.ic.ac.uk/" target="_blank">Juan Gallego's group</a> at Imperial College London, where I am involved in experimental and data science projects related to neurotechnology, BCIs, and the neuroscience of motor control. <br> <br> 
  Previously, I completed my PhD at Dartmouth College in the lab of <a href="http://www.vandermeerlab.org/" target="_blank">Matthijs van der Meer</a> where I studied the flexible processing of motivationally-relevant information in the rodent nucleus accumbens. Before Dartmouth, I started my research career with <a href="https://www.wlu.ca/academics/faculties/faculty-of-science/faculty-profiles/bruce-mckay/index.html" target="_blank">Bruce McKay</a> at Wilfrid Laurier University where I investigated the effects of the abused solvent toluene on various aspects of neural function. See <a href="https://www.jimmiegmaz.com/resume" target="_self">Resume</a> for more information. <br> <br> 
  I am passionate about using technology to improve health outcomes, and aim to use my expertise to contribute to the development of innovative therapies.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://scholar.google.com/citations?user=7NL96I4AAAAJ&hl=en

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
